### PR TITLE
adds onSwipe prop

### PR DESCRIPTION
**Pull request by khoerling**
- triggers immediately when swipe is successful
- passes currentIndex

### CODE REVIEW

**Comment by VGoose** [comment]
Looks good! Could you resubmit with the new function added to propTypes?  

What do you think about renaming it to onSwipeStart to not confuse it with the onSwipe method?

**Comment by khoerling** [comment]
Fast reply and excellent software-- certainly, commit 8d5f520 squares up the remainder.  Let me know if you'd like to see anything else,

KH

**Comment by VGoose** [comment]
Please add onSwipeStart to Swiper.propTypes and I'll merge it 👍

**Comment by khoerling** [comment]
Oops-- it's there now.  Let me know if you would prefer a rebase,

K

**Comment by VGoose** [comment]
Thanks for contributing! Accepted.

**Pull request merged**
