### PR TITLE
adds onPressed fn

### PR DESCRIPTION
**Pull request by khoerling**
- useful when card is pressed (and not moved)
- allows more flexible behaviors

### CODE REVIEW

**Comment by khoerling** [comment]
also, would be sweet to see a shiny new release with everything!

**Comment by VGoose** [comment]
Cool, this looks like a good addition; I can definitely see use cases for this. 

What do you think of this: 
```javascript
        else {
          if (dx <= 5 && dy <= 5) {
            this.props.onPressed(currentIndex)
          }
          this.animateReset({ vx: vx, vy: vy })
        }
```
I haven't gotten to play on it with a phone so I'm not sure if users will be able to consistently press without moving the card, this would let us add a slight buffer.  I chose 5 for no particular reason.

**Comment by VGoose** [comment]
I thought about it some more and I think we should approach it differently.  

We could add
 ```
onMoveShouldSetPanResponder: (e, gestureState) => true,
```
This will allow the card to have touchables and at the same time be swipeable, still. 
I think this is the more extensible approach; users can compose their cards with touchables if they would like. What do you think?

**Comment by khoerling** [comment]
Thank you for the in-depth critique!  After playing around with this a bit more, using derivative values dx, dy of 0 (no movement) feels most natural for pressing;  also, it's simpler requiring no animateReset.

onMoveShouldSetPanResponder is a more flexible solution.

**Pull request closed without merging**
